include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_use_package_imports: false
    prefer_relative_imports: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    always_put_required_named_parameters_first: false