name: pull_down_button
description: A package that implements Menus from iOS 14 in Flutter. Highly customizable.
version: 1.0.0-alpha.01
homepage: https://github.com/notDmDrl/pull_down_button
repository: https://github.com/notDmDrl/pull_down_button
issue_tracker: https://github.com/notDmDrl/pull_down_button/issues
publish_to: "none" # block publishing

topics:
  - cupertino
  - menu

environment:
  sdk: ">3.3.0-0 <4.0.0"
  flutter: ">=3.19.0-0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.11.0

dev_dependencies:
  very_good_analysis: ^5.1.0
